EDIT TB_SUBS

EDIT TB_ORDER



-- 구독 테이블에 MD_NO FK 제약조건 삭제

ALTER TABLE tb_subs DROP CONSTRAINT FK_TB_MD_TO_TB_SUBS;

-- 구독 테이블 MD_NO 컬럼 삭제

ALTER TABLE TB_SUBS DROP COLUMN MD_NO;

-- 구독 테이블에 ORDER_NO 컬럼 추가

CREATE TABLE SELLERMOON.TB_SUBS
( ORDER_NO    VARCHAR2(100 BYTE) DEFAULT ' ' );

-- 구독 테이블에 ORDER_NO FK 제약조건 설정

ALTER TABLE SELLERMOON.TB_SUBS ADD (
  CONSTRAINT FK_TB_ORDER_TO_TB_SUBS
  FOREIGN KEY (ORDER_NO) 
  REFERENCES SELLERMOON.TB_ORDER (ORDER_NO)
  ENABLE VALIDATE);
  
 COMMIT;
 
 --- 다시 보낼게요